### ISSUE TITLE
Restart hung process

### ISSUE THREAD

**Issue by rorymadden** [google/import-mailbox-to-gmail#10]
Hi, my computer hibernated overnight and the process has hung after loading 15000 mail messages. Is there any way to re-start the process from the point it has hung?

**Comment by eesheesh** [comment]
Unfortunately not, but if you have proper message IDs on your messages in the mbox files, it shouldn't cause any duplicates to restart the process.

If you had multiple mbox files, you can save some time by removing the ones that were completed (based on the log file).

I'll take this as a feature request to add the option to restart an import that was stopped. Thanks!

**Comment by linusliang** [comment]
I'd also love this feature =) I have a 15gig MBOX file and it stopped halfway!

**Comment by eesheesh** [comment]
This was added.
