### ISSUE TITLE
Can manage to get it installed on Fedora 22

### ISSUE THREAD

**Issue by icolR** [google/import-mailbox-to-gmail#11]
Hi 
your tool is amazing and it works fine for me on Windows 7.
Thanks for that 
Nevertheless it doesn't work on Fedora 22. It seems that I can't manage to install sudo pip install --upgrade google-api-python-client PyOpenSSL

thank for your help.

this is my error trace : 

 gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o

```
c/_cffi_backend.c:2:20: erreur fatale: Python.h : Aucun fichier ou dossier de ce type

compilation terminée.

error: command 'gcc' failed with exit status 1

----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-BUYb8R/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1FFo7X-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-BUYb8R/cff
```

**Comment by eesheesh** [comment]
According to [this page](https://bitbucket.org/cffi/cffi/issues/38/sudo-pip-install-cffi-fails-under-ubuntu), you need to install `python-dev` (might be a different name on Fedora) for this to work.

Let me know if it works. Thanks!

**Comment by burhan** [comment]
The correct package is `python-devel`.

**Comment by eesheesh** [comment]
Python issue, not an issue with this script.
