### ISSUE TITLE
Make a new release to include the fix for issue #9

### ISSUE THREAD

**Issue by jbm1** [google/import-mailbox-to-gmail#12]
I read about nested labels support in issue #9 and expected that by downloading and running the script linked from README.md, such support would work.

However, this is currently not the case, as the latest release linked from README.md is 1.3, which was built before the fix for #9.

Please consider making a new release and update the download link in README.md.

**Comment by eesheesh** [comment]
Done. :) https://github.com/google/import-mailbox-to-gmail/releases/tag/v1.4
