### ISSUE TITLE
Seems not to install correctly!

### ISSUE THREAD

**Issue by jalalcharaf** [google/import-mailbox-to-gmail#18]
Hi there,

I hope my post is not too stupid for you guys.

I am writing to ask what is wrong in the installation as I get this error at the command line:
fatal error C1083

What could have gone wrong?

Is there a way I can just reinstall the whole thing?

Jalal

**Comment by eesheesh** [comment]
This is a MSVC error, doesn't seem related to this script. If you're still seeing this, please include the exact command you're running and the full output. Thanks!
