### ISSUE TITLE
readme.md has stale instructions for setting up credentials

### ISSUE THREAD

**Issue by cmurf** [google/import-mailbox-to-gmail#3]
Steps 4-15 seem stale because the UI I'm seeing doesn't match up with the steps. There's an "API Manager" and on the left there's Overview and Credentials. Clicking on Overview there's Popular APIs including Gmail.

Clicking on Credentials, it's "New credentials" pop-down, then "Service account key". To create a service account key, there's a service account pop-up with options "App Engine default service account" and "Compute Engine default service account" and "New Service Account" The readme doesn't make it clear which of those three I'm supposed to pick. So I chose "New Service Account" and then Close as stated in step 10.

Step 11 makes no sense because there is no service account email address where I'm left off at the end of step 10. I'm still in credentials, and there is a list of service account keys, with one key that has an ID with a long number, but there's no email address.

Step 12 there is nothing called "Client ID" on this page. There is an "ID" field with a long number, but this number plugged into Step 14 yields "This client name has not been registered with Google yet."

If I go back to API Manager > Credentials, on the right is "Manage service accounts" if I click that there's a list of accounts "App engine default service account" and "Compute Engine default service account" and "gmailmigrate" which is the one I created in step 9, and here there is an email address, but it's not clickable. Nothing on this line is clickable. There is still no Client ID or Client Name anywhere on this page.

So...stuck.

Ok finally this is what worked:

API Manager > Credentials > Manage service accounts, find "gmailmigrate" and on far right side is a hamburger dots pull down menu to edit the service account, do that. Check "Enable Google Apps Domain-wide Delegation" give it a name, click save. And NOW there is a "View Client ID" option for "gmailmigrate" and that number works in step 13.

**Comment by crelegant** [comment]
Thanks your post helped me. But, still I am stuck on the last step of importing. Nothing happens when I run the command. Can you help?

**Comment by eesheesh** [comment]
Hi,

Thanks for reporting this! I hope to get around to fixing it in the next few days. In the meantime, you can use https://support.google.com/a/answer/6291304 as a base for the correct instructions - that article suggest enabling more APIs and scopes than import-mailbox-to-gmail needs, though.

**Comment by cmurf** [comment]
@crelegant No idea, I think clues should be in the log file. I had lots of failures at first, but the log file contained sufficient clues to figure it all out, and it was always some sort of user error. The section B step 3 item to use pip install, I also had some failures that likewise need to be corrected for before things will work - that was easier to sort out on OS X than on Linux, but ultimately I got the script to work on both OS X and Linux without much difficulty at the CLI; mostly I was confounded in Google's console.

**Comment by crelegant** [comment]
Can you add me on Skype where we can chat and sort this out?
