### ISSUE TITLE
Import Failed Messages?

### ISSUE THREAD

**Issue by infatuation-psa** [google/import-mailbox-to-gmail#33]
Hey, I just used this software and it worked pretty much perfectly! I have a question though. My internet dropped during part of the sync, and thus, quite a few messages failed to sync. Anyone have an idea of how to sync these failed messages? I have the log file so I could filter/find which ones failed, but I'm not sure as to how to remove the successful ones from the mbox file in order to re-sync without doubling the messages.

**Comment by ratchet132** [comment]
I'm also getting a server connection error from the account I synced to. I'm assuming this is due to it uh processing 6000 emails that were just added, but I'm not sure.

**Comment by eesheesh** [comment]
Hi,

1. You can set the tool to start from a certain message using the `--from_message` parameter, see [the documentation](https://github.com/google/import-mailbox-to-gmail#options-and-notes). You can then stop the migration when the affected messages were processed. There's no automated way to do this, currently.

2. If you share the exact error here, I can take a look. :)

**Comment by ratchet132** [comment]
The error is fixed now, so I think it was just due to the large amount of processing :)
Is there a way to stop at a certain message, or only start?

**Comment by eesheesh** [comment]
Great! :)

No, there's no option to stop execution at a certain message, but it should be easy to add that. If you'd like, feel free to send me a pull request with the change.

**Comment by priyaruby86** [comment]
Watch this video, it may helps you: https://youtu.be/beNmXaXQkr4

**Comment by ar45** [comment]
> Watch this video, it may helps you: https://youtu.be/beNmXaXQkr4

STOP DIRECTING PEOPLE TO OUTSIDE SOURCES NOT RELATED TO THIS REPO!

**Comment by eesheesh** [comment]
I've removed a comment that suggested using Thunderbird to upload messages to Gmail. This isn't a good suggestion - doing that would quickly make you go over the [Gmail IMAP daily upload bandwidth limit](https://support.google.com/a/answer/1071518#Notification__Videoconference_Covid19__Timestamp:~:text=IMAP,-500) of 500mb. (thanks @ar45!)


I'm also going to close this issue, as there hasn't been a response in 2+ years. If you encounter any issues, please report a new one.
