### ISSUE TITLE
import-mailbox-to-gmail.py: error: argument --dir is required

### ISSUE THREAD

**Issue by jwebbstevens** [google/import-mailbox-to-gmail#34]
I get an error message running the test that I setup for this.

import-mailbox-to-gmail.py: error: argument --dir is required

Is this the directory of the mbox or the directory of the python script?

**Comment by PMox** [comment]
When in doubt, you can run the script with --help to see the meaning of the various options.

The meaning of --dir is: "Path to the directory that contains user directories with mbox files to import"

**Comment by jwebbstevens** [comment]
Thanks @PMox that is very helpful.  Perhaps it's something with how apple mail handled the Export process of the mbox?

I'm pretty sure my file path is accurate since the script is running, the target mbox appers to throw the script off.

When I exported the mbox from Apple mail (i used the trash folder which had only one email in it for testing purposes) this is how I structured the file path. I kept the script and the target folder for the mbox in the same folder on the desktop.

`python /Users/computer/Desktop/import-mailbox/import-mailbox-to-gmail.py --json /Users/computer /Desktop/import-mailbox/Gmail API-87b47b451bb4.json -- dir /Users/computer/Desktop/import-mailbox/mbox`

I noticed the Apple Mail exporter created a [GMAIL] folder inbetween the email address and the actual mbox file. Does that matter?

so the mbox folder looks like

/mbox
/mbox/email@email.com
/mbox/email@email.com/[GMAIL]
/mbox/email@email.com/[GMAIL]/imported messages.mbox.

I noticed the instructions don't call for that middle folder but if I remove it and put the mbox right in the email@email.com folder I still get that dir error.

I think I'm structuring something wrong.

**Comment by jwebbstevens** [comment]
Ugh...I'm an idiot I had an extra space between -- and dir

**Comment by jwebbstevens** [comment]
it worked.  i also learn Google reserves the word trash.  So had to rename to a different label.  this is pretty slick.  thank you all for creating/contributing to this.

**Comment by jwebbstevens** [comment]
Here's the file structure I used....

mbox
mbox/email@email.com
mbox/email@email.com/Trash.mbox

and then within that mbox are two files mbox and table_of_contents respectively.

This is exported from Apple mail running on the latest Apple OS.

This is the ERROR message I get

> 13:29:20 ERROR get_label_id_from_name@import-mailbox-to-gmail.py Can't create label 'Trash' for user email@email.com
Traceback (most recent call last):
  File "/Users/computer/Desktop/import-mailbox/import-mailbox-to-gmail.py", line 153, in get_label_id_from_name
    body=label_object).execute(num_retries=args.num_retries)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/googleapiclient/http.py", line 844, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 400 when requesting https://www.googleapis.com/gmail/v1/users/email@email.com/labels?alt=json returned "Invalid label name">
13:29:20 ERROR process_mbox_files@import-mailbox-to-gmail.py Skipping label 'Trash' because it can't be created'

email and device name changed for privacy purposes.  i think i can run a deeper debug so if that provides more information and helps i will.

Also I have the _Trash_ label in Gmail set to **hide** but it is checked off to show in IMAP.

Does **show/hide** impact the ability to import to that specific label?  Now that I think of it that might be it.

**Comment by jwebbstevens** [comment]
I tried to show the "Trash" label in Gmail and it still Errored.  Same error listed above.

**Comment by eesheesh** [comment]
I think I found the issue - can you try to download [the new version of the script](https://github.com/google/import-mailbox-to-gmail/raw/master/import-mailbox-to-gmail.py) and see if importing a file called "Trash.mbox" works now?

Thanks!

**Comment by jwebbstevens** [comment]
I gave this a shot thanks. But it didn't work. I downloaded [the new version of the script ](https://github.com/google/import-mailbox-to-gmail/raw/master/import-mailbox-to-gmail.py) moved some messages that were not imported in previous runs to Trash in Apple Mail. 

Used Apple Mail to Export the mailbox to an .mbox.  Opened the mbox file in a text editor and confirmed that one of the messages not previously imported is in the .mbox file.

I then ran the new script with debug level four. Here's the result....

`13:39:50 INFO main @import-mailbox-to-gmail.py *** Starting import-mailbox-to-gmail 1.4 on Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] ***
13:39:50 INFO main @import-mailbox-to-gmail.py Arguments:
13:39:50 INFO main @import-mailbox-to-gmail.py 	auth_host_name: 'localhost'
13:39:50 INFO main @import-mailbox-to-gmail.py 	auth_host_port: [8080, 8090]
13:39:50 INFO main @import-mailbox-to-gmail.py 	dir: '/Users/macbook/Desktop/import-mailbox/mbox/email @email.com/Trash.mbox'
13:39:50 INFO main @import-mailbox-to-gmail.py 	fix_msgid: True
13:39:50 INFO main @import-mailbox-to-gmail.py 	from_message: 0
13:39:50 INFO main @import-mailbox-to-gmail.py 	httplib2debuglevel: 4
13:39:50 INFO main @import-mailbox-to-gmail.py 	json: '/Users/macbook/Desktop/import-mailbox/ JSON'
13:39:50 INFO main @import-mailbox-to-gmail.py 	log: 'import-mailbox-to-gmail-78454.log'
13:39:50 INFO main @import-mailbox-to-gmail.py 	logging_level: 'INFO'
13:39:50 INFO main @import-mailbox-to-gmail.py 	noauth_local_webserver: False
13:39:50 INFO main @import-mailbox-to-gmail.py 	num_retries: 10
13:39:50 INFO main @import-mailbox-to-gmail.py 	replace_quoted_printable: True
13:39:50 INFO main @import-mailbox-to-gmail.py *** Done importing all users from directory '/Users/macbook/Desktop/import-mailbox/mbox/email@email.com/Trash.mbox'
13:39:50 INFO main @import-mailbox-to-gmail.py *** Import summary:
13:39:50 INFO main @import-mailbox-to-gmail.py     0 users imported with no failures
13:39:50 INFO main @import-mailbox-to-gmail.py     0 users imported with some failures
13:39:50 INFO main @import-mailbox-to-gmail.py     0 users failed
13:39:50 INFO main @import-mailbox-to-gmail.py     0 labels (mbox files) imported with no failures
13:39:50 INFO main @import-mailbox-to-gmail.py     0 labels (mbox files) imported with some failures
13:39:50 INFO main @import-mailbox-to-gmail.py     0 labels (mbox files) failed
13:39:50 INFO main @import-mailbox-to-gmail.py     0 messages imported successfully
13:39:50 INFO main @import-mailbox-to-gmail.py     0 messages failed

13:39:50 INFO main @import-mailbox-to-gmail.py Finished.`

I modified the data above to retain privacy but the above is essentially the log  

Unfortunately with the latest build zero message was imported into the Trash label for Gmail (that is the native Trash label in Gmail, not one I created)

**Comment by eesheesh** [comment]
As far as I can tell, the issue in this case is that you used `--dir /Users/macbook/Desktop/import-mailbox/mbox/email @email.com/Trash.mbox` and it should just have been `--dir /Users/macbook/Desktop/import-mailbox/mbox`.

The way you had it, the directory structure should be something like `/Users/macbook/Desktop/import-mailbox/mbox/email@email.com/Trash.mbox/email@email.com/Trash.mbox`. :)

**Comment by jwebbstevens** [comment]
Thanks.  I fixed my folder structure and it worked.  The script found the messages and threw them in the Gmail Trash label.  Problem solved (still stuck with Apple Mail Export Mailbox on [Attachments](https://github.com/google/import-mailbox-to-gmail/issues/35) though.) I have to send them another disk image.  Other users are reporting it on the Apple Forums so it's not just me and must be something with High Sierra's latest build of Apple Mail 😞

**Comment by eesheesh** [comment]
Excellent, thanks for confirming!
