### ISSUE TITLE
Duplicate labels created when importing nested mboxes

### ISSUE THREAD

**Issue by junikowski** [google/import-mailbox-to-gmail#36]
Thanks for the incredibly useful tool!

Issue
=====

While importing nested folders is not documented in README.md, it seems to work nonetheless, with a small caveat.

While using this tool to migrate an user's multi-level nested mboxes from a macOS Mail install to Gmail, I noticed that while the hierarchy was ultimately correctly reproduced on Gmail, a duplicate of each label was also created, with the entire hierarchy flattened at the root of the label list on Gmail. This means that one has to manually go in and delete all of these duplicates or write a script to do so programmatically. 

The source of this seems to be the call to `get_label_id_from_name()` in `process_mbox_files()` while looping on dirs before files (at line 185). Since the dirs outputted by os_walk only contain the name of the dir, not the full path thereof, a bunch of 0-level labels are created which are not later populated. Indeed, the second call to `get_label_id_from_name()`, which properly includes the nested hierarchy, re-creates the label and populates those.

In my specific case, commenting out the loop on `dirs` enabled me to avoid this problem. However, the first call to `get_label_id_from_name()` in this label may have another purpose that I have not encountered (e.g. triggering `"Labels under '%s' may not nest correctly"` error logging, or dealing with the way other clients export mboxes). As such, it should be possible to edit this first call to ressemble the second one. I have opened a PR re/ this issue at #37.

Note on nested folders exporting with macOS Mail
================================================

One can export macOS Mail folders while preserving their hierarchy by expanding all subfolders in the UI, selecting both subfolders and parents at the same time, and exporting all of those together. If one does so, the resulting file hierarchy looks as follows (for 2 levels of depth) :

`Parent_Name (dir)`
`-- Child_Name (dir)`
`---- GrandChild_Name.mbox`
`------ mbox (file)`
`------ table_of_contents (file)`
`-- Child_Name.mbox (dir)`
`---- mbox (file)`
`---- table_of_contents (file)`
`Parent_Name.mbox (dir)`
`-- mbox (file)`
`-- table_of_contents (file)`

macOS mail creates mbox files even if a folder has no emails stored inside of it (i.e. the mbox file for the parents, in the corresponding .mbox directory, will have a size of 0 octets).

An interesting property of this for users of this tool is that given that `os.walk` is used for listing mbox files, mbox files contained in a nested folder will be detected. Since the `get_label_id_from_name` function is called with the var labelname, which itself is based on the full path minus the folder path, the nested labels created by the `get_label_id_from_name()` function will be named like so: Parent_Name/Child_Name. The result in the Gmail UI is that if both the Parent_Name and Parent_Name/Child_Name labels are created (which will happen even if the parent has 0 messages, since a mbox file is still created by macOS Mail), the two labels are properly collapsed both in the Gmail UI and over IMAP. This looks intentional on the author's part but is not documented in the README.md.

**Comment by eesheesh** [comment]
Good catch, thanks!

**Comment by junikowski** [comment]
Thanks! Would it be worth documenting the nested folder exporting thing in the readme file? It might be useful to others.

**Comment by eesheesh** [comment]
Well, it should "just work". :) Do you mean documenting how to export hierarchy from Apple Mail? Or how to import it using the script?

As for how labels are created with the script - I intentionally had it create a label for each folder, otherwise nesting wouldn't work (I did it incorrectly, which you now fixed). The fact that Apple Mail also creates an mbox for each folder (even if empty) means that this isn't needed for Apple Mail exports, but it's still useful if you just have a directory structure with mbox files (not from an Apple Mail export).

Let me know if I addressed your suggestion, or if I missed anything.

Thanks for the fix!

**Comment by junikowski** [comment]
I meant the former; which arguably has less to do with this script than with Apple Mail :)

**Comment by eesheesh** [comment]
As a lot of people are using this script to import from Apple Mail, and we already mention it in the readme, feel free to send a PR to add your tip in https://github.com/google/import-mailbox-to-gmail/blob/master/README.md#options-and-notes. :)

**Comment by junikowski** [comment]
Done!
