### ISSUE TITLE
Instructions are out of date or n/a

### ISSUE THREAD

**Issue by l-g** [google/import-mailbox-to-gmail#49]
I have a googlealumni.com account (but obviously I am not admin of the whole googlealumni.com-domain) and would like to import some mbox:es into that account. Following the instructions for this project...well, it breaks down completely quite early on. Either they are outdated or things work **very** differently if you are just a user rather than an admin of a GSuite account.

It would be very nice if the instructions were updated/adopted to regular users too.

**Comment by eesheesh** [comment]
Hi,

This tool is indeed only meant for admins, so you wouldn't be able to follow the steps if you aren't an admin.

If that's the case, you can try https://github.com/google/mail-importer, which is designed for use by end users.

Good luck! :)
