### ISSUE TITLE
File in use error on Windows7x64

### ISSUE THREAD

**Issue by bio5admin** [google/import-mailbox-to-gmail#5]
I believe I setup everything correctly and didn't get any errors along the way... any guidance would be great....?

![win-7_x64](https://cloud.githubusercontent.com/assets/1799610/12934776/5be6c818-cf4e-11e5-8ec5-6fb20665a9c3.png)

**Comment by bio5admin** [comment]
Issue not resolved, however I changed gears and got the ubuntu 15.10.  

Yes the first half of the API setup is a little out of date, but I was able to successfully modify the domain to get the keys working.  

Recommendation on ubuntu's- the repo version of python didn't work I had to download and build like the instructions stated. Make sure you get most of the dependencies set(I couldn't resolve a few), before you running make install pyhton. 

I also had to change Thunderbird’s file extensions to .mbox all my files had .msf (must be updated)

I got it to work

**Comment by bio5admin** [comment]
My windows issue had something to do with the extraction of the zip. I re-downloaded and unzipped another copy and it seemed to work.

**Comment by crelegant** [comment]
I followed all the steps. Still, the emails were not imported. It just created a folder. Is this working for you?

**Comment by eesheesh** [comment]
What do you see in the log?

**Comment by crelegant** [comment]
Seeing this error **HttpError 400**

**Comment by eesheesh** [comment]
I answered this in [issue #4](https://github.com/google/import-mailbox-to-gmail/issues/4#issuecomment-185700654), let's move the discussion there.
