### ISSUE TITLE
How to show original sent date

### ISSUE THREAD

**Issue by GiacomoDD** [google/import-mailbox-to-gmail#55]
Hi, importing mbox files, the Gmail message is not showing the original sent date, but importing one. Is there a way to fix this issue? I read this [old post on StackOverflow](https://stackoverflow.com/questions/28849438/set-internaldatesource-in-gmail-api-message-upload), but I don't know if it is still possibile to implement that solution..
Thanks

**Comment by eesheesh** [comment]
Hi,

As you can see in [line 267](https://github.com/google/import-mailbox-to-gmail/blob/855760d56be3bf941afe5722f66374c1185c5729/import-mailbox-to-gmail.py#L267), the script uses `dateHeader` as the [internal date source](https://developers.google.com/gmail/api/reference/rest/v1/InternalDateSource). That means that the "received date" you'll see in Gmail is the date in the message's `Date` header.

Gmail API doesn't provide a way to specify a separate "received date", it can either be the date when the message was imported, or parsed from the `Date` header.

Even if using the `dateHeader` option, you might still see the import date as the message's "received date", if Gmail failed to parse the `Date` header during the import. Please check the message you're importing and see if the date is [formatted correctly as per RFC822](https://www.w3.org/Protocols/rfc822/#z28).

**Comment by GiacomoDD** [comment]
Ah, thank you so much for your suggestion. Actually I'm not a developer, so I'm trying to figure out how to do this formatting check, but it's a little bit hard and cofusing..

**Comment by eesheesh** [comment]
If you have an mbox file, it's just a text file, that you should be able to open with any text editor. Then, look for the affected message (i.e. a message where you saw the wrong date in Gmail), and take a look at the line starting with `Date:` at the top of that message.

You'd often see that there's no such line at all, or it's there but formatted incorrectly (for example, date as "16/8/2022" instead of "16 Aug 2022").

**Comment by GiacomoDD** [comment]
Thank you @eesheesh for your precious help. Yesterday I finally was able to make everything work, importing all the mbox files into the Gmail accounts. I'm not sure what happened, because I didn't modify anyone of the mbox files. But in the end it worked.
Thanks again for your support!
