### ISSUE TITLE
cannot import name SignedJwtAssertionCredentials

### ISSUE THREAD

**Issue by darrmitchell** [google/import-mailbox-to-gmail#8]
python ./import-mailbox-to-gmail.py --json credentials.json --dir ./mbox/
Traceback (most recent call last):
  File "./import-mailbox-to-gmail.py", line 33, in <module>
    from oauth2client.client import SignedJwtAssertionCredentials
ImportError: cannot import name SignedJwtAssertionCredentials

I'm no developer, but Google seems to think SignedJwtAssertionCredentials is deprecated? Running on Mac OS X 10.11.3

**Comment by eesheesh** [comment]
Are you using the [latest version](https://github.com/google/import-mailbox-to-gmail/releases/tag/v1.3)?

**Comment by darrmitchell** [comment]
Nope. That fixed it. I clicked the version in the readme on the front page:

Download the script - import-mailbox-to-gmail.py

Sorry about that.
