### ISSUE TITLE
label:question Is it possible to import to nested labels?

### ISSUE THREAD

**Issue by josjonkers** [google/import-mailbox-to-gmail#9]

**Comment by eesheesh** [comment]
It should be possible if you can get a file with  `/` in the name, which should be possible on Linux/Mac, and maybe on Windows as well (but I don't know if it would work). I never tested it, though.

I'll take this issue as a feature request to add proper support for it using subfolders. Thanks!

**Comment by eesheesh** [comment]
If you want to test it before the release, you can download the fixed version from [here](https://github.com/google/import-mailbox-to-gmail/raw/master/import-mailbox-to-gmail.py). If you do, please let me know if you encounter any issues. Thanks!

**Comment by josjonkers** [comment]
Works as expected! Good Job!

I used the path:
C:\mbox\address@domain.com\NewFolder1\Testlabel.mbox
Any messages that were already imported will not be overwritten, but do get the new label attached.

**Comment by eesheesh** [comment]
Great, thanks for testing! It's expected for messages to not get overwritten and only get the new label.
